name: packer

on:
  push:

env:
  PRODUCT_VERSION: "latest"

permissions:
  contents: read
  id-token: write

jobs:
  packer:
    runs-on: ubuntu-latest
    environment: Prod
    name: Run Packer
    steps:
      # OIDC login
      - name: Azure Login
        id: login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v2
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `packer build`
        id: build
        run: "packer build -force ."

  # custom-packer:
  #   runs-on: ubuntu-latest
  #   environment: Prod
  #   container:
  #     image: davodgd/custom-packer:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     # OIDC login
  #     - name: Azure Login
  #       id: login
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUSCRIPTION_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  #     - name: Run `packer init`
  #       id: init
  #       run: "packer init ."

  #     - name: Run `packer validate`
  #       id: validate
  #       run: "packer validate ."

  #     - name: Run `packer build`
  #       id: build
  #       run: "packer build -force ."
